# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - priority
  - bug
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hi there! It looks like this issue hasn't had any activity for a while.
  It will be closed if no further activity occurs. If you think your issue
  is still relevant, feel free to comment on it to keep it open.
  Thanks!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Hi there! It looks like this issue hasn't had any activity for a while.
  To keep things tidy, I am going to close this issue for now.
  If you think your issue is still relevant, just leave a comment
  and I will reopen it.
  Thanks!
