name: PouchDP
description: File a support request for the PouchDB adapter
labels: pouchdb

# note: markdown sections will NOT appear as part of the issue as per documentation, rather they provide context to the user
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#markdown


body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
        ### Important :exclamation:
        Please help us maintain this project more efficiently! Before creating the issue make sure you shouldn't be creating it in one the below repos instead:
        - Core related: https://github.com/nextauthjs/next-auth
        - Docs related: https://github.com/nextauthjs/docs
        
        If you are in the correct repo, then proceed by providing the following information:
  - type: input
    id: title
    attributes:
      label: Title
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce ☕️ 
      description: Please provide a link or code snippets to a minimal reproduction of the bug
    validations:
      required: true 
  - type: markdown
    attributes:
      value: |
        We encourage you to use one of the templates set up on **CodeSandbox** to reproduce your issue:
        - [`next-auth-example`](https://codesandbox.io/s/next-auth-example-1kktb)
        - [`next-auth-typescript-example`](https://codesandbox.io/s/next-auth-typescript-example-se32w)

        🚧 – _If you don't provide any way to reproduce the bug, the issue is at risk of being closed._
      
  - type: textarea
    id: description
    attributes: 
      label: Your question/bug report 📓
      description: Please provide a more in-depth description of your request.
    validations:
      required: true    
  - type: dropdown
    id: contributing
    attributes: 
      label: Contributing  🙌🏽
      description: Are you willing to open a PR for this?
      multiple: false
      options:
        - "Yes, I am"
        - "No, I'm afraid I cannot help regarding this"
    validations:
      required: true
  - type: markdown
    attributes: 
      value: |
        It takes a lot of work 🏋🏻‍♀️ maintaining a library like `next-auth`; any contribution is more than welcome 💚
        
       
