name: CI

on:
  push:
    branches:
      - canary
  pull_request:
    branches:
      - canary

jobs:
  # From https://github.com/marketplace/actions/workflow-run-cleanup-action
  # This action cleans up previously running instances of a workflow on the same branch.
  # This accomplishes the task of automatically cancelling CI runs on pushes to the same branch,
  # which is a common feature in most CI systems but currently not possible with GitHub actions.
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'adapters' output variable
      adapters: ${{ steps.filter.outputs.changes }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            prisma: packages/prisma/**
            fauna: packages/fauna/**
            dynamodb: packages/dynamodb/**
            typeorm-legacy: packages/typeorm-legacy/**
            prisma-legacy: packages/prisma-legacy/**
  test-adapters:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.adapters != '[]'
    strategy:
      matrix:
        adapter: ${{ fromJSON(needs.changes.outputs.adapters) }}
    defaults:
      run:
        working-directory: ./packages/${{ matrix.adapter }}
    env:
      CI: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - uses: bahmutov/npm-install@v1
      - name: test ${{ matrix.adapter }}
        run: yarn test
  publish:
    needs: test-adapters
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - uses: bahmutov/npm-install@v1
      - name: Build
        run: yarn build
      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Canary
        if: github.event_name == 'push'
        run: yarn lerna publish --canary --preid canary --dist-tag canary --yes --no-verify-access
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish PR
        if: github.event_name == 'pull_request'
        run: yarn lerna publish --canary --preid pr.${{github.event.number}} --dist-tag pr-${{github.event.number}} --yes --no-verify-access
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
